import type { BuildingProject, StakeholderRole } from "./types";

// Public-facing role list. Admin intentionally absent — admin is never publicly
// selectable per docs/IA_SPEC.md §8.5; admin role is granted via backend/scripts/grant_admin.py only.
export const roles: Array<{ id: StakeholderRole; label: string; promise: string }> = [
  { id: "resident", label: "Resident", promise: "Prepaid solar tokens when your apartment is capacity-cleared and ATS-active." },
  { id: "homeowner", label: "Homeowner", promise: "Prepaid home energy after LBRS — savings and external monetization only; no host royalty on your own roof." },
  { id: "building_owner", label: "Building Owner", promise: "Turn your building into an energy site." },
  { id: "provider", label: "Provider", promise: "Deploy panels and infrastructure into qualified demand." },
  { id: "financier", label: "Financier", promise: "Fund named infrastructure deals." },
  { id: "electrician", label: "Electrician", promise: "Execute verified energy deployments." },
];

export const demoProjects: BuildingProject[] = [
  {
    id: "nyeri-ridge-a",
    name: "Nyeri Ridge A",
    locationBand: "Nyeri, peri-urban",
    units: 24,
    stage: "funding",
    buildingKind: "apartment",
    energy: {
      arrayKw: 18,
      peakSunHours: 5.5,
      systemEfficiency: 0.82,
      batteryKwh: 28,
      batteryDepthOfDischarge: 0.86,
      batteryRoundTripEfficiency: 0.9,
      monthlyDemandKwh: 2340,
      daytimeDemandFraction: 0.52,
    },
    solarPriceKes: 20,
    gridPriceKes: 28,
    settlementRates: {
      reserve: 0.05,
      providers: 0.3,
      financiers: 0.45,
      owner: 0.06,
      emappa: 0.14,
    },
    drs: {
      siteKind: "apartment",
      demandCoverage: 84,
      prepaidCommitment: 78,
      loadProfile: 82,
      installationReadiness: 76,
      installerReadiness: 90,
      capitalAlignment: 81,
      projectedUtilization: 0.74,
      hasPrepaidFunds: true,
      hasResidentDemandSignal: true,
      hasCertifiedLeadElectrician: true,
      solarApartmentCapacityFitVerified: true,
      apartmentAtsMeterMappingVerified: true,
      atsKplcSwitchingVerified: true,
      ownerPermissionsComplete: true,
      hasVerifiedSupplierQuote: true,
      siteInspectionComplete: true,
      capacityPlanApproved: true,
      stakeholdersVetted: true,
      electricianLaborPaymentResolved: true,
      contractsAndComplianceReady: true,
      monitoringConnectivityResolved: true,
      settlementDataTrusted: true,
    },
    providerOwnership: [
      { ownerId: "provider-solartech", ownerRole: "provider", percentage: 0.7 },
      { ownerId: "resident-pool", ownerRole: "resident", percentage: 0.3 },
    ],
    financierOwnership: [{ ownerId: "financier-kijani", ownerRole: "financier", percentage: 1 }],
    capitalRequiredKes: 1280000,
    fundedKes: 870000,
    prepaidCommittedKes: 184000,
    operationalWorkflows: [
      {
        id: "ats_activation",
        label: "ATS activation queue",
        status: "in_review",
        ownerRole: "electrician",
        detail: "12 of 24 apartments are capacity-cleared for the first activation phase; ATS visits are queued behind LBRS.",
        evidenceLabel: "Capacity plan + ATS/PAYG map",
        prototypeScope: true,
      },
      {
        id: "verification_documents",
        label: "Owner/site verification docs",
        status: "ready",
        ownerRole: "building_owner",
        detail: "Roof access, owner authority, and meter-area permissions are represented as accepted pilot evidence.",
        evidenceLabel: "Authority packet",
        prototypeScope: true,
      },
      {
        id: "quote_reservation",
        label: "Quote reservation",
        status: "ready",
        ownerRole: "provider",
        detail: "Verified BOM quote is reserved for this named building; no production stock lock is executed in pilot mode.",
        evidenceLabel: "BOM quote lock",
        prototypeScope: true,
      },
      {
        id: "delivery_evidence",
        label: "Delivery and field evidence",
        status: "in_review",
        ownerRole: "electrician",
        detail: "Serials, DB photos, roof photos, and apartment switching evidence are tracked as expected proof rows.",
        evidenceLabel: "Photo/serial pack",
        prototypeScope: true,
      },
      {
        id: "go_live_signoff",
        label: "Go-live signoff",
        status: "pending",
        ownerRole: "admin",
        detail: "Ops signoff waits for LBRS, token-state simulation, settlement dry run, and launch packet approval.",
        evidenceLabel: "LBRS signoff grid",
        prototypeScope: true,
      },
      {
        id: "kyc_escrow",
        label: "KYC / escrow status",
        status: "prototype",
        ownerRole: "financier",
        detail: "Financier capital is shown as named-building commitment; real KYC/KYB and escrow rails are not integrated.",
        evidenceLabel: "Pilot disclosure",
        prototypeScope: true,
      },
      {
        id: "ai_evidence_ingestion",
        label: "AI evidence ingestion",
        status: "prototype",
        ownerRole: "admin",
        detail: "AI ingestion is a visible ops placeholder only; gate decisions still require explicit accepted evidence.",
        evidenceLabel: "Evidence queue placeholder",
        prototypeScope: true,
      },
    ],
  },
  {
    id: "karatina-court",
    name: "Karatina Court",
    locationBand: "Karatina, mixed-use",
    units: 16,
    stage: "review",
    buildingKind: "apartment",
    energy: {
      arrayKw: 9,
      peakSunHours: 5.2,
      systemEfficiency: 0.8,
      batteryKwh: 10,
      batteryDepthOfDischarge: 0.82,
      batteryRoundTripEfficiency: 0.88,
      monthlyDemandKwh: 1680,
      daytimeDemandFraction: 0.36,
    },
    solarPriceKes: 21,
    gridPriceKes: 28,
    settlementRates: {
      reserve: 0.06,
      providers: 0.34,
      financiers: 0.38,
      owner: 0.06,
      emappa: 0.16,
    },
    drs: {
      siteKind: "apartment",
      demandCoverage: 63,
      prepaidCommitment: 58,
      loadProfile: 61,
      installationReadiness: 72,
      installerReadiness: 80,
      capitalAlignment: 66,
      projectedUtilization: 0.59,
      hasPrepaidFunds: true,
      hasResidentDemandSignal: true,
      hasCertifiedLeadElectrician: true,
      solarApartmentCapacityFitVerified: true,
      apartmentAtsMeterMappingVerified: true,
      atsKplcSwitchingVerified: true,
      ownerPermissionsComplete: true,
      hasVerifiedSupplierQuote: false,
      siteInspectionComplete: true,
      capacityPlanApproved: true,
      stakeholdersVetted: true,
      electricianLaborPaymentResolved: true,
      contractsAndComplianceReady: true,
      monitoringConnectivityResolved: true,
      settlementDataTrusted: true,
    },
    providerOwnership: [{ ownerId: "provider-mwangaza", ownerRole: "provider", percentage: 1 }],
    financierOwnership: [{ ownerId: "financier-catalyst", ownerRole: "financier", percentage: 1 }],
    capitalRequiredKes: 740000,
    fundedKes: 220000,
    prepaidCommittedKes: 46000,
    operationalWorkflows: [
      {
        id: "ats_activation",
        label: "ATS activation queue",
        status: "blocked",
        ownerRole: "electrician",
        detail: "Capacity review is blocked until quote validity and utilization clear DRS.",
        evidenceLabel: "Capacity review",
        prototypeScope: true,
      },
      {
        id: "verification_documents",
        label: "Owner/site verification docs",
        status: "in_review",
        ownerRole: "building_owner",
        detail: "Owner authority is accepted for review, but the launch packet is not complete.",
        evidenceLabel: "Authority packet",
        prototypeScope: true,
      },
      {
        id: "quote_reservation",
        label: "Quote reservation",
        status: "blocked",
        ownerRole: "provider",
        detail: "Supplier quote is missing, so hardware readiness and stock reservation cannot count toward DRS.",
        evidenceLabel: "Missing BOM quote",
        prototypeScope: true,
      },
      {
        id: "delivery_evidence",
        label: "Delivery and field evidence",
        status: "pending",
        ownerRole: "electrician",
        detail: "Delivery proof, serials, and field photos wait for a valid quote and deployment schedule.",
        evidenceLabel: "Photo/serial pack",
        prototypeScope: true,
      },
      {
        id: "go_live_signoff",
        label: "Go-live signoff",
        status: "pending",
        ownerRole: "admin",
        detail: "LBRS and launch-packet signoff cannot begin while DRS remains blocked.",
        evidenceLabel: "LBRS signoff grid",
        prototypeScope: true,
      },
      {
        id: "kyc_escrow",
        label: "KYC / escrow status",
        status: "prototype",
        ownerRole: "financier",
        detail: "Capital status is pilot-only; no real escrow, suitability, or payment release integration exists.",
        evidenceLabel: "Pilot disclosure",
        prototypeScope: true,
      },
      {
        id: "ai_evidence_ingestion",
        label: "AI evidence ingestion",
        status: "prototype",
        ownerRole: "admin",
        detail: "AI evidence routing is visible as an ops placeholder, not an automated approval path.",
        evidenceLabel: "Evidence queue placeholder",
        prototypeScope: true,
      },
    ],
  },
];
