import type { BuildingProject, StakeholderRole } from "./types";

// Public-facing role list. Admin intentionally absent — admin is never publicly
// selectable per docs/IA_SPEC.md §8.5; admin role is granted via backend/scripts/grant_admin.py only.
export const roles: Array<{ id: StakeholderRole; label: string; promise: string }> = [
  { id: "resident", label: "Resident", promise: "Cheaper prepaid solar with grid fallback." },
  { id: "building_owner", label: "Building Owner", promise: "Turn your building into an energy site." },
  { id: "provider", label: "Provider", promise: "Deploy panels and infrastructure into qualified demand." },
  { id: "financier", label: "Financier", promise: "Fund named infrastructure deals." },
  { id: "electrician", label: "Electrician", promise: "Execute verified energy deployments." },
];

export const demoProjects: BuildingProject[] = [
  {
    id: "nyeri-ridge-a",
    name: "Nyeri Ridge A",
    locationBand: "Nyeri, peri-urban",
    units: 24,
    stage: "funding",
    energy: {
      arrayKw: 18,
      peakSunHours: 5.5,
      systemEfficiency: 0.82,
      batteryKwh: 28,
      batteryDepthOfDischarge: 0.86,
      batteryRoundTripEfficiency: 0.9,
      monthlyDemandKwh: 2340,
      daytimeDemandFraction: 0.52,
    },
    solarPriceKes: 20,
    gridPriceKes: 28,
    settlementRates: {
      reserve: 0.05,
      providers: 0.3,
      financiers: 0.45,
      owner: 0.06,
      emappa: 0.14,
    },
    drs: {
      demandCoverage: 84,
      prepaidCommitment: 78,
      loadProfile: 82,
      installationReadiness: 76,
      installerReadiness: 90,
      capitalAlignment: 81,
      projectedUtilization: 0.74,
      hasPrepaidFunds: true,
      hasCertifiedLeadElectrician: true,
      meterInverterMatchResolved: true,
      ownerPermissionsComplete: true,
      hasVerifiedSupplierQuote: true,
      monitoringConnectivityResolved: true,
      settlementDataTrusted: true,
    },
    providerOwnership: [
      { ownerId: "provider-solartech", ownerRole: "provider", percentage: 0.7 },
      { ownerId: "resident-pool", ownerRole: "resident", percentage: 0.3 },
    ],
    financierOwnership: [{ ownerId: "financier-kijani", ownerRole: "financier", percentage: 1 }],
    capitalRequiredKes: 1280000,
    fundedKes: 870000,
    prepaidCommittedKes: 184000,
  },
  {
    id: "karatina-court",
    name: "Karatina Court",
    locationBand: "Karatina, mixed-use",
    units: 16,
    stage: "review",
    energy: {
      arrayKw: 9,
      peakSunHours: 5.2,
      systemEfficiency: 0.8,
      batteryKwh: 10,
      batteryDepthOfDischarge: 0.82,
      batteryRoundTripEfficiency: 0.88,
      monthlyDemandKwh: 1680,
      daytimeDemandFraction: 0.36,
    },
    solarPriceKes: 21,
    gridPriceKes: 28,
    settlementRates: {
      reserve: 0.06,
      providers: 0.34,
      financiers: 0.38,
      owner: 0.06,
      emappa: 0.16,
    },
    drs: {
      demandCoverage: 63,
      prepaidCommitment: 58,
      loadProfile: 61,
      installationReadiness: 72,
      installerReadiness: 80,
      capitalAlignment: 66,
      projectedUtilization: 0.59,
      hasPrepaidFunds: true,
      hasCertifiedLeadElectrician: true,
      meterInverterMatchResolved: true,
      ownerPermissionsComplete: true,
      hasVerifiedSupplierQuote: false,
      monitoringConnectivityResolved: true,
      settlementDataTrusted: true,
    },
    providerOwnership: [{ ownerId: "provider-mwangaza", ownerRole: "provider", percentage: 1 }],
    financierOwnership: [{ ownerId: "financier-catalyst", ownerRole: "financier", percentage: 1 }],
    capitalRequiredKes: 740000,
    fundedKes: 220000,
    prepaidCommittedKes: 46000,
  },
];
